# Generated by Django 3.2.3 on 2022-01-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='to_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='from_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_date',
            field=models.DateTimeField(),
        ),
    ]
