# Generated by Django 3.2.3 on 2022-01-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0002_auto_20220101_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='password',
            field=models.CharField(default='', max_length=32),
        ),
    ]
