# Generated by Django 3.2.3 on 2022-01-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0003_event_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.BigIntegerField()),
                ('participant_email', models.EmailField(max_length=254)),
                ('registration_type', models.CharField(max_length=20)),
                ('no_of_people', models.IntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManager.event')),
            ],
        ),
    ]
