# Generated by Django 3.2.3 on 2022-03-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0006_rename_name_participant_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('admin', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=500)),
                ('poster_link', models.URLField()),
                ('admin_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ClubMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('semester', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Member', 'Member')], max_length=20)),
                ('contact_no', models.BigIntegerField()),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManager.club')),
            ],
        ),
    ]
