# Generated by Django 3.2.3 on 2022-03-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManager', '0007_club_clubmembers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmembers',
            old_name='semester',
            new_name='position',
        ),
    ]
